version: '3'
services:
  bot:
    container_name: bot
    image: ghcr.io/the0mikkel/ollama-discord-bot:latest
    restart: always
    stop_grace_period: 1s
    env_file:
      - bot.env
    networks:
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - redis:/data
    networks:
      - redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  redis:

volumes:
  redis:
