name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
    release:
        name: Release
        uses: the0mikkel/ci/.github/workflows/semver-release.yml@v1.1.4

    docker:
        name: Docker
        needs: 
            - release
        if: needs.release.outputs.version != '' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: the0mikkel/ci/.github/workflows/docker.yml@v1.1.4
        with:
            semver: ${{ needs.release.outputs.version }}

    docker-prerelease:
        name: Docker pre-release
        needs: 
            - release
        if: needs.release.outputs.version != '' && github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: the0mikkel/ci/.github/workflows/docker.yml@v1.1.4
        with:
            tags: type=raw,value=${{ needs.release.outputs.version }}